checks:
    php: true
    javascript: true

filter:
    paths:
        - 'includes/'
        - 'admin/'
        - 'js/src/'
        - 'wp-typography.php'
    dependency_paths:
        - wordpress/
    excluded_paths:
        - 'js/*.min.js'

build:
    cache:
        directories:
            - ~/.composer   # Composer home directory (avoid fetching already fetched packages)
            # vendor is already included.

    environment:
        rabbitmq: false
        mysql: false
        postgresql: false
        mongodb: false
        elasticsearch: false
        redis: false
        memcached: false
        neo4j: false
        php:
            version: 7.4
    nodes:
        analysis:
            project_setup:
                override: true
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress-core --no-update --no-interaction
                    - composer update --no-interaction
            tests:
                override:
                    - php-scrutinizer-run
                    - phpcs-run -p wp-typography.php includes/ admin/ --extensions=php
                    - js-scrutinizer-run --enable-security-analysis
                    - eslint-run


tools:
    php_code_sniffer: false
    php_cs_fixer: false
    external_code_coverage: true
